permalink: pretty
theme: jekyll_patternbot

patterbot:
  title: "CanGrow"
  description: |
    A company designed to connect patients and growers, while also educating patients on how to grow cannabis themselves.
  font_url: "https://fonts.googleapis.com/css?family=Hind+Madurai:400,700|Patua+One&display=swap"
